config/routes.rb
Rails.application.routes.draw do
  
  resources :vehiculos
  resources :modulos
  resources :perfiles
  resources :perfiles

  get 'alternativas/index'

  get 'alternativas/menu0'

  get 'alternativas/menu1'

  get 'alternativas/menu2'

  get 'alternativas/menu3'

  get 'alternativas/menu4'

  get 'alternativa/index'


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  resources :movies do
    collection do
    	get 'search'
    end	
  	resources :reviews, except: [:show, :index]
  end	
  
  root 'movies#index'
  
end

app/models/vehiculo.rb
class Vehiculo < ActiveRecord::Base
end

app/controllers/vehiculos_controller.rb
class VehiculosController < ApplicationController
  before_action :set_vehiculo, only: [:show, :edit, :update, :destroy]

  # GET /vehiculos
  # GET /vehiculos.json
  def index
    @vehiculos = Vehiculo.all
  end

  # GET /vehiculos/1
  # GET /vehiculos/1.json
  def show
  end

  # GET /vehiculos/new
  def new
    @vehiculo = Vehiculo.new
  end

  # GET /vehiculos/1/edit
  def edit
  end

  # POST /vehiculos
  # POST /vehiculos.json
  def create
    @vehiculo = Vehiculo.new(vehiculo_params)

    respond_to do |format|
      if @vehiculo.save
        format.html { redirect_to @vehiculo, notice: 'Vehiculo was successfully created.' }
        format.json { render :show, status: :created, location: @vehiculo }
      else
        format.html { render :new }
        format.json { render json: @vehiculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehiculos/1
  # PATCH/PUT /vehiculos/1.json
  def update
    respond_to do |format|
      if @vehiculo.update(vehiculo_params)
        format.html { redirect_to @vehiculo, notice: 'Vehiculo was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehiculo }
      else
        format.html { render :edit }
        format.json { render json: @vehiculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehiculos/1
  # DELETE /vehiculos/1.json
  def destroy
    @vehiculo.destroy
    respond_to do |format|
      format.html { redirect_to vehiculos_url, notice: 'Vehiculo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehiculo
      @vehiculo = Vehiculo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehiculo_params
      params.require(:vehiculo).permit(:marca, :modelo, :anio)
    end
end

app/helpers/vehiculos_helper.rb
module VehiculosHelper
end

app/views/vehiculos/_form.html.erb
<%= form_for(@vehiculo) do |f| %>
  <% if @vehiculo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehiculo.errors.count, "error") %> prohibited this vehiculo from being saved:</h2>

      <ul>
      <% @vehiculo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :marca %><br>
    <%= f.text_field :marca %>
  </div>
  <div class="field">
    <%= f.label :modelo %><br>
    <%= f.text_field :modelo %>
  </div>
  <div class="field">
    <%= f.label :anio %><br>
    <%= f.number_field :anio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vehiculos/edit.html.erb
<h1>Editing Vehiculo</h1>

<%= render 'form' %>

<%= link_to 'Show', @vehiculo %> |
<%= link_to 'Back', vehiculos_path %>

app/views/vehiculos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Vehiculos</h1>

<table>
  <thead>
    <tr>
      <th>Marca</th>
      <th>Modelo</th>
      <th>Anio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehiculos.each do |vehiculo| %>
      <tr>
        <td><%= vehiculo.marca %></td>
        <td><%= vehiculo.modelo %></td>
        <td><%= vehiculo.anio %></td>
        <td><%= link_to 'Show', vehiculo %></td>
        <td><%= link_to 'Edit', edit_vehiculo_path(vehiculo) %></td>
        <td><%= link_to 'Destroy', vehiculo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehiculo', new_vehiculo_path %>

app/views/vehiculos/new.html.erb
<h1>New Vehiculo</h1>

<%= render 'form' %>

<%= link_to 'Back', vehiculos_path %>

app/views/vehiculos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Marca:</strong>
  <%= @vehiculo.marca %>
</p>

<p>
  <strong>Modelo:</strong>
  <%= @vehiculo.modelo %>
</p>

<p>
  <strong>Anio:</strong>
  <%= @vehiculo.anio %>
</p>

<%= link_to 'Edit', edit_vehiculo_path(@vehiculo) %> |
<%= link_to 'Back', vehiculos_path %>