config/routes.rb
Rails.application.routes.draw do
  
  resources :vehiculos
  resources :modulos
  resources :perfiles
  resources :perfiles

  get 'alternativas/index'

  get 'alternativas/menu0'

  get 'alternativas/menu1'

  get 'alternativas/menu2'

  get 'alternativas/menu3'

  get 'alternativas/menu4'

  get 'alternativa/index'


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  resources :movies do
    collection do
    	get 'search'
    end	
  	resources :reviews, except: [:show, :index]
  end	
  
  root 'movies#index'
  
end

app/models/modulo.rb
class Modulo < ActiveRecord::Base
end

app/controllers/modulos_controller.rb
class ModulosController < ApplicationController
  before_action :set_modulo, only: [:show, :edit, :update, :destroy]

  # GET /modulos
  # GET /modulos.json
  def index
    @modulos = Modulo.all
  end

  # GET /modulos/1
  # GET /modulos/1.json
  def show
  end

  # GET /modulos/new
  def new
    @modulo = Modulo.new
  end

  # GET /modulos/1/edit
  def edit
  end

  # POST /modulos
  # POST /modulos.json
  def create
    @modulo = Modulo.new(modulo_params)

    respond_to do |format|
      if @modulo.save
        format.html { redirect_to @modulo, notice: 'Modulo was successfully created.' }
        format.json { render :show, status: :created, location: @modulo }
      else
        format.html { render :new }
        format.json { render json: @modulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /modulos/1
  # PATCH/PUT /modulos/1.json
  def update
    respond_to do |format|
      if @modulo.update(modulo_params)
        format.html { redirect_to @modulo, notice: 'Modulo was successfully updated.' }
        format.json { render :show, status: :ok, location: @modulo }
      else
        format.html { render :edit }
        format.json { render json: @modulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /modulos/1
  # DELETE /modulos/1.json
  def destroy
    @modulo.destroy
    respond_to do |format|
      format.html { redirect_to modulos_url, notice: 'Modulo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_modulo
      @modulo = Modulo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def modulo_params
      params.require(:modulo).permit(:name, :descripcion)
    end
end

app/helpers/modulos_helper.rb
module ModulosHelper
end

app/views/modulos/_form.html.erb
<%= form_for(@modulo) do |f| %>
  <% if @modulo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@modulo.errors.count, "error") %> prohibited this modulo from being saved:</h2>

      <ul>
      <% @modulo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/modulos/edit.html.erb
<h1>Editing Modulo</h1>

<%= render 'form' %>

<%= link_to 'Show', @modulo %> |
<%= link_to 'Back', modulos_path %>

app/views/modulos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Modulos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @modulos.each do |modulo| %>
      <tr>
        <td><%= modulo.name %></td>
        <td><%= modulo.descripcion %></td>
        <td><%= link_to 'Show', modulo %></td>
        <td><%= link_to 'Edit', edit_modulo_path(modulo) %></td>
        <td><%= link_to 'Destroy', modulo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Modulo', new_modulo_path %>

app/views/modulos/new.html.erb
<h1>New Modulo</h1>

<%= render 'form' %>

<%= link_to 'Back', modulos_path %>

app/views/modulos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @modulo.name %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @modulo.descripcion %>
</p>

<%= link_to 'Edit', edit_modulo_path(@modulo) %> |
<%= link_to 'Back', modulos_path %>