config/routes.rb
Rails.application.routes.draw do
  
  resources :vehiculos
  resources :modulos
  resources :perfiles
  resources :perfiles

  get 'alternativas/index'

  get 'alternativas/menu0'

  get 'alternativas/menu1'

  get 'alternativas/menu2'

  get 'alternativas/menu3'

  get 'alternativas/menu4'

  get 'alternativa/index'


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  resources :movies do
    collection do
    	get 'search'
    end	
  	resources :reviews, except: [:show, :index]
  end	
  
  root 'movies#index'
  
end

app/models/perfile.rb
class Perfile < ActiveRecord::Base
end

app/controllers/perfiles_controller.rb
class PerfilesController < ApplicationController
  before_action :set_perfile, only: [:show, :edit, :update, :destroy]

  # GET /perfiles
  # GET /perfiles.json
  def index
    @perfiles = Perfile.all
  end

  # GET /perfiles/1
  # GET /perfiles/1.json
  def show
  end

  # GET /perfiles/new
  def new
    @perfile = Perfile.new
  end

  # GET /perfiles/1/edit
  def edit
  end

  # POST /perfiles
  # POST /perfiles.json
  def create
    @perfile = Perfile.new(perfile_params)

    respond_to do |format|
      if @perfile.save
        format.html { redirect_to @perfile, notice: 'Perfile was successfully created.' }
        format.json { render :show, status: :created, location: @perfile }
      else
        format.html { render :new }
        format.json { render json: @perfile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /perfiles/1
  # PATCH/PUT /perfiles/1.json
  def update
    respond_to do |format|
      if @perfile.update(perfile_params)
        format.html { redirect_to @perfile, notice: 'Perfile was successfully updated.' }
        format.json { render :show, status: :ok, location: @perfile }
      else
        format.html { render :edit }
        format.json { render json: @perfile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /perfiles/1
  # DELETE /perfiles/1.json
  def destroy
    @perfile.destroy
    respond_to do |format|
      format.html { redirect_to perfiles_url, notice: 'Perfile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_perfile
      @perfile = Perfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def perfile_params
      params.require(:perfile).permit(:name, :nivel)
    end
end

app/helpers/perfiles_helper.rb
module PerfilesHelper
end

app/views/perfiles/_form.html.erb
<%= form_for(@perfile) do |f| %>
  <% if @perfile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@perfile.errors.count, "error") %> prohibited this perfile from being saved:</h2>

      <ul>
      <% @perfile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :nivel %><br>
    <%= f.number_field :nivel %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/perfiles/edit.html.erb
<h1>Editing Perfile</h1>

<%= render 'form' %>

<%= link_to 'Show', @perfile %> |
<%= link_to 'Back', perfiles_path %>

app/views/perfiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Perfiles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Nivel</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @perfiles.each do |perfile| %>
      <tr>
        <td><%= perfile.name %></td>
        <td><%= perfile.nivel %></td>
        <td><%= link_to 'Show', perfile %></td>
        <td><%= link_to 'Edit', edit_perfile_path(perfile) %></td>
        <td><%= link_to 'Destroy', perfile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Perfile', new_perfile_path %>

app/views/perfiles/new.html.erb
<h1>New Perfile</h1>

<%= render 'form' %>

<%= link_to 'Back', perfiles_path %>

app/views/perfiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @perfile.name %>
</p>

<p>
  <strong>Nivel:</strong>
  <%= @perfile.nivel %>
</p>

<%= link_to 'Edit', edit_perfile_path(@perfile) %> |
<%= link_to 'Back', perfiles_path %>